exports.messageList = {
  M001: "Please enter all required fields.",
  M002: "User already exists",
  M003: "User singup successfully",
  M004: "User logged in successfully",
  M005: "User logged out successfully",
  M006: "User deleted successfully",
  M007: "User updated successfully",
  M008: "User not found",
  M009: "wrong credentials",
  M010: "error in signup",
  M011: "error in update user",
  M012: "User deleted successfully",
  M013: "User list fetched successfully",
  M014: "Please enter field to update.",
  M015: "Error in adding expense",
  M016: "Expense added successfully",
  M017: "Expense list fetched successfully",
  M018: "Expense deleted successfully",
  M019: "Expense updated successfully",
  M020: "Expense not found",
  M021: "Group created successfully",
  M022: "Group updated successfully",
  M023: "Group deleted successfully",
  M024: "Group list fetched successfully",
  M025: "Error in creating group",
  M026: "Error in updating group",
  M027: "Error in deleting group",
  M028: "Error in fetching group list",
  M029: "Error in fetching expense list",
  M030: "settle up successfully",
  M031: "Error in settle up",
  M032: "Data fetched successfully",
};
